### ISSUE TITLE
KeyError for pandoc-fignos 0.16

### ISSUE THREAD

**Issue by hasufell** [tomduck/pandoc-fignos#28]
With python2 I get

```
$ ./create_pdf.sh SonarQube_Regeln.md
Traceback (most recent call last):
  File "/home/hasufell/.local/bin/pandoc-fignos", line 11, in <module>
    load_entry_point('pandoc-fignos==0.16', 'console_scripts', 'pandoc-fignos')()
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandoc_fignos.py", line 357, in main
    detach_attrs_image], doc)
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandoc_fignos.py", line 355, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandocfilters.py", line 34, in walk
    array.append(walk(item, action, format, meta))
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandocfilters.py", line 39, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandocfilters.py", line 39, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandocfilters.py", line 39, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/home/hasufell/.local/lib/python2.7/site-packages/pandocfilters.py", line 25, in walk
    res = action(item['t'], item['c'], format, meta)
KeyError: 'c'
pandoc: Error running filter pandoc-fignos
Filter returned error status 1
```

With python3:

```
$ ./create_pdf.sh SonarQube_Regeln.md
pandoc: Error running filter pandoc-fignos
fd:4: hPutBuf: resource vanished (Broken pipe)
```

The script I run is:

``` sh
#!/bin/sh

die() {
    echo "$1"
    exit 1
}

[[ -z $1 ]] && die "missing arguments, usage: create_pdf.sh <input-file> [output-file]"

input="${1}"
output="${2:-${input%.*}.pdf}"
pandoc=${pandoc:-pandoc}

${pandoc} \
    -t latex \
    --template=default.latex \
    --toc \
    -f markdown+yaml_metadata_block+tex_math_dollars \
    --filter pandoc-fignos \
    -o ${output} \
    ${input}
```

**Comment by tomduck** [comment]
Hi @hasufell.  Thanks for your feedback.  I just pushed out a new version.  Could you please check to see if it works?  If you are getting the same error, then a minimal example (including the markdown) that exposes the error would be very helpful.

**Comment by jottr** [comment]
I am also seeing a similar error. Not sure if it is related: 

```
pandoc --latex-engine=xelatex --filter=pandoc-fignos report.md --out report.pdf
Traceback (most recent call last):
  File "/Users/jottr/.pyenv/versions/2.7.11/bin/pandoc-fignos", line 9, in <module>
    load_entry_point('pandoc-fignos==0.17.1', 'console_scripts', 'pandoc-fignos')()
  File "/Users/jottr/.pyenv/versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandoc_fignos.py", line 353, in main
    meta = doc[0]['unMeta']
KeyError: 0
pandoc: Error running filter pandoc-fignos
Filter returned error status 1
make: *** [pdf] Error 83

```

This is with a freshly installed `pandoc-fignos` via pip.

**Comment by jrlil** [comment]
I have a different error, but *fignos* also fails to run a *.md* to *.docx* conversion.Here's what I see when running *fignos* before *citeproc*. When I run *fignos* before *tablenos*, the error is similar, but concernes *tablenos* instead of *citeproc*. *Tablenos* works fine.

```
pandoc: Error running filter pandoc-citeproc
Error in $[16][0]: cannot unpack array of length 7 into a 3-tuple
CallStack (from HasCallStack):
  error, called at pandoc.hs:153:46 in main:Main
```

**Comment by tomduck** [comment]
Thanks, @jottr.  I think that you have the same bug as in [Issue #30](https://github.com/tomduck/pandoc-fignos/issues/30).  I am presently working on a fix for it.

**Comment by tomduck** [comment]
@jottr: Issue #30 is fixed.  Please let me know if it works for you.

**Comment by tomduck** [comment]
@hasufell: I just pushed out a new version that works with pandoc 1.18. Could you please check to see if the problem you were having is resolved?  If it is no longer relevant, then please go ahead and close this Issue.  Thanks.

**Comment by tomduck** [comment]
Did the new version work for you, @hasufell?

**Comment by tomduck** [comment]
Hi @hasufell.  I re-reading the initial issue, I see that an older version of pandoc-fignos is being used.  I would guess that an upgrade should correct the problems.

If the bug resurfaces, please feel welcome to re-open this Issue.

Cheers,
Tom
