### ISSUE TITLE
pandoc-attributes install error

### ISSUE THREAD

**Issue by slhck** [tomduck/pandoc-fignos#42]
I'm getting an error trying to install this on Ubuntu 16.04 with Python 3.5 and latest `pip`.

```
pip3 install --upgrade --pre pandoc-fignos
Collecting pandoc-fignos
  Downloading pandoc-fignos-1.0.0rc1.tar.gz
Collecting pandoc-xnos>=0.11 (from pandoc-fignos)
  Downloading pandoc-xnos-0.11.tar.gz
Collecting pandocfilters (from pandoc-fignos)
  Downloading pandocfilters-1.4.2.tar.gz
Collecting pandoc-attributes (from pandoc-fignos)
  Downloading pandoc-attributes-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qi1xad7m/pandoc-attributes/setup.py", line 5, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/home/werner/.local/lib/python3.5/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qi1xad7m/pandoc-attributes/
```

Any idea what might cause this?

**Comment by slhck** [comment]
Just realized this is actually an issue with `pandoc-attributes`, same as this: https://github.com/aaren/pandoc-attributes/issues/1

Uninstalling pypandoc solves the issue.

**Comment by tomduck** [comment]
Thanks for this feedback, @slhck.  To work around the bug, I copied `pandocattributes.py` into the `pandoc-xnos` project.

I just pushed out a new release candidate for `pandoc-fignos`, which you can install with pip using the `--pre` flag.  It requires the new pandoc-xnos 0.13, and installs whether or not pypandoc is in place.
