### ISSUE TITLE
'list' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by onevcat** [tomduck/pandoc-fignos#8]
Hi, thanks for the great filter. But I encountered an issue while using it.

Markdown:

```
[*Hello*](http://hello.com) world
```

Run with pandoc-fignos (0.7.3) and pandoc (1.16.0.2)

``` bash
pandoc test.md --filter pandoc-fignos
```

Gives me an error:

```
Traceback (most recent call last):
  File "python/bin/pandoc-fignos", line 9, in <module>
    load_entry_point('pandoc-fignos==0.7.3', 'console_scripts', 'pandoc-fignos')()
  File "python/lib/python3.5/site-packages/pandoc_fignos.py", line 290, in main
    doc)
  File "python/lib/python3.5/site-packages/pandoc_fignos.py", line 288, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "python/lib/python3.5/site-packages/pandocfilters.py", line 34, in walk
    array.append(walk(item, action, format, meta))
  File "python/lib/python3.5/site-packages/pandocfilters.py", line 25, in walk
    res = action(item['t'], item['c'], format, meta)
  File "python/lib/python3.5/site-packages/pandoc_fignos.py", line 207, in preprocess
    newvalue = repair_broken_refs(value)
  File "python/lib/python3.5/site-packages/pandoc_fignos.py", line 158, in repair_broken_refs
    value[i+1]['t'], value[i+1]['c']):
  File "python/lib/python3.5/site-packages/pandoc_fignos.py", line 140, in is_broken_ref
    return key1 == 'Link' and value1[1][0]['c'].endswith('{@eq') \
AttributeError: 'list' object has no attribute 'endswith'
pandoc: Error running filter pandoc-fignos
Filter returned error status 1
```

Any idea on this?

**Comment by tomduck** [comment]
Thanks for your Issue report!  I have reproduced the bug and am working on a fix.

**Comment by tomduck** [comment]
I just pushed pandoc-fignos 0.7.4 to pypi.  If you find the fix works, please go ahead and close this Issue.

Thanks for your kind words about the filter.  :o)

**Comment by onevcat** [comment]
0.7.4 solved this like a charm! Thank you!
