### ISSUE TITLE
TypeError when running pandoc-fignos with Pandoc 2.10

### ISSUE THREAD

**Issue by dhimmel** [tomduck/pandoc-fignos#81]
Upgrading to [Pandoc 2.10](https://github.com/jgm/pandoc/releases/tag/2.10) produced the following [error](https://github.com/manubot/rootstock/runs/832032746#step:7:28) in our Pandoc command:

```
[INFO] Running filter pandoc-fignos
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/pandoc-fignos", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandoc_fignos.py", line 645, in main
    altered)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandoc_fignos.py", line 642, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 844, in process_refs
    _process_refs(value[-5], pattern, labels)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 92, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 746, in _process_refs
    if v['t'] == 'Cite' and len(v['c']) == 2:
TypeError: string indices must be integers
Error running filter pandoc-fignos:
Filter returned error status 1
```

Possibly related to https://github.com/tomduck/pandoc-xnos/issues/16

**Comment by tomduck** [comment]
Thanks for your report.  There was an AST change with pandoc 2.10.  I have updated the `nextrelease` branch accordingly.  If this problem persists after the next release of pandoc-fignos, please feel welcome to open this issue.

Cheers,
Tom

**Comment by tomduck** [comment]
pandoc-fignos 2.3.0 is now released.  --Tom
