### ISSUE TITLE
Installation in Ubuntu 14.04

### ISSUE THREAD

**Issue by joseah** [tomduck/pandoc-fignos#9]
After installing `python-pip` and `setuptools` as root, the following errors are shown:

``` bash
pip install pandoc-fignos 
```

``` bash
Downloading/unpacking pandoc-fignos
  Downloading pandoc-fignos-0.7.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pandoc-fignos/setup.py) egg_info for package pandoc-fignos

    warning: no files found matching 'demos/img/today.png'
    warning: no files found matching 'demos/img/yesterday.png'
    warning: no files found matching 'demos/img/earlier.png'
Downloading/unpacking pandocfilters (from pandoc-fignos)
  Downloading pandocfilters-1.3.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pandocfilters/setup.py) egg_info for package pandocfilters

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1235, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 465, in assert_source_matches_version
    % (display_path(self.source_dir), version, self))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 70, in display_path
    if path.startswith(os.getcwd() + os.path.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
```

The version of Ubuntu is:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty

Not sure how to solve this.
Thanks.

**Comment by tomduck** [comment]
Fixed.  I forgot to update entries in the MANIFEST.in that pypi requires.  Sorry about that.

Thank you for filing this Issue.  Please close if it the fix works for you.

**Comment by joseah** [comment]
The installation was successful this time. Thank you very much for your time and your work.

**Comment by tomduck** [comment]
Excellent! Thanks for your kind words.
